name: Docker CI

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  IMAGE_NAME: vittoscaletta/curcash

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u vittoscaletta -p 1Q2w3e4r5t

      - name: Build Docker image
        run: |
          docker build -t vittoscaletta/curcash:latest .
          docker tag vittoscaletta/curcash:latest vittoscaletta/curcash:$(git rev-parse --short HEAD)

      - name: Push Docker image
        run: |
          docker push vittoscaletta/curcash:latest
          docker push vittoscaletta/curcash:$(git rev-parse --short HEAD)

      - name: Stop and remove previous container
        run: |
          docker stop curcash-container || true
          docker rm curcash-container || true

      - name: Run new container
        run: |
          docker run -d -p 8080:80 --name curcash-container vittoscaletta/curcash:latest