name: Docker CI

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  IMAGE_NAME: vitalinkakalinka/curcash

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USER" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$(git rev-parse --short HEAD)

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$(git rev-parse --short HEAD)

      - name: Stop and remove previous container
        run: |
          docker stop curcash-container || true
          docker rm curcash-container || true

      - name: Run new container
        run: |
          docker run -d -p 8080:80 --name curcash-container $IMAGE_NAME:latest